# Generated by Django 2.2.6 on 2019-11-05 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_is_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='카테고리명')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('낮음', '낮음'), ('중간', '중간'), ('높음', '높음')], default='낮음', max_length=10, verbose_name='난이도'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='위도'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='longtitude',
            field=models.FloatField(default=0, verbose_name='경도'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.Coach', verbose_name='코치'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5, verbose_name='별점')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.Project', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='좋아요시간')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='projects.Project', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_project', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField(verbose_name='1주차')),
                ('second', models.TextField(verbose_name='2주차')),
                ('third', models.TextField(verbose_name='3주차')),
                ('fourth', models.TextField(verbose_name='4주차')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='projects.Project', verbose_name='프로젝트')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='projects.Question', verbose_name='question')),
            ],
        ),
    ]
