# Generated by Django 2.2.6 on 2019-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191107_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_image',
            field=models.ImageField(blank=True, default='account/IC-EMPTY_PROFILE@2x.png', upload_to='projects/title_image/%Y/%m/%d', verbose_name='대표 이미지'),
        ),
    ]
