# Generated by Django 2.2.6 on 2019-12-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.Category', verbose_name='카테고리'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], default=0, max_length=10, verbose_name='상태'),
        ),
    ]
