# Generated by Django 2.2.6 on 2019-12-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20191203_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_intro',
        ),
        migrations.AddField(
            model_name='project',
            name='project_DayinWeek',
            field=models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], default='월', max_length=2, verbose_name='프로젝트 요일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_caution',
            field=models.TextField(default='a', verbose_name='유의 사항'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_goal',
            field=models.TextField(default='a', verbose_name='프로젝트 목표'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_reward',
            field=models.TextField(default='a', verbose_name='목표 달성 보상'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_reward_condition',
            field=models.TextField(default='a', verbose_name='보상 조건'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_shortIntro',
            field=models.TextField(default='a', verbose_name='프로젝트 한 줄 소개'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_term',
            field=models.IntegerField(default='4', verbose_name='프로젝트 기간'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_special', models.TextField(verbose_name='특별한 점')),
                ('project_process', models.TextField(verbose_name='프로젝트 진행')),
                ('project_toLearn', models.TextField(verbose_name='배우게 될 점')),
                ('project_acquisition', models.TextField(verbose_name='얻을 수 있는 것')),
                ('project_recommend', models.TextField(verbose_name='추천 대상')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='프로젝트')),
            ],
        ),
    ]
