# Generated by Django 2.2.6 on 2019-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191211_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_term',
            field=models.IntegerField(default=4, verbose_name='프로젝트 기간'),
        ),
    ]
