# Generated by Django 2.2.6 on 2019-12-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20191211_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='first',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='second',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='third',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='content',
            field=models.TextField(default='안녕하세요', verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='week',
            field=models.IntegerField(default=1, verbose_name='주차'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='projects.Project', verbose_name='프로젝트'),
        ),
    ]
