# Generated by Django 2.2.6 on 2019-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20191213_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('입문', '입문'), ('심화', '심화'), ('전문가', '전문가')], max_length=10, verbose_name='난이도'),
        ),
    ]
