# Generated by Django 2.2.6 on 2019-12-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20191224_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(blank=True, default='https://s3.ap-northeast-2.amazonaws.com/maint.img/media/accounts/user/2019/12/24/default_user.png', upload_to='projects/title_image/%Y/%m/%d', verbose_name='대표 이미지'),
        ),
    ]
