# Generated by Django 2.2.6 on 2020-01-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200106_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sale_price',
            field=models.PositiveIntegerField(default=0, verbose_name='할인 금액'),
        ),
    ]
