# Generated by Django 2.2.6 on 2020-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(verbose_name='모집 마감일'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_startTime',
            field=models.DateField(verbose_name='프로젝트 시작 날짜'),
        ),
    ]
