# Generated by Django 2.2.6 on 2020-02-25 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200225_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='모집 마감일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_startTime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='프로젝트 시작 날짜'),
            preserve_default=False,
        ),
    ]
