# Generated by Django 2.2.6 on 2020-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', '비활성'), ('1', '모집 중'), ('2', '모집 마감'), ('3', '진행 중')], default=0, max_length=10, verbose_name='상태'),
        ),
    ]
