# Generated by Django 2.2.6 on 2020-03-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20200317_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='user',
            new_name='users',
        ),
    ]
