# Generated by Django 2.2.6 on 2020-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200317_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(blank=True, default='projects/title_image/2019/12/23/Project_default.png', upload_to='projects/title_image/%Y/%m/%d', verbose_name='대표 이미지'),
        ),
    ]
