# Generated by Django 2.2.6 on 2020-04-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20200413_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='project_DayinWeek',
        ),
    ]
