# Generated by Django 2.2.6 on 2020-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_remove_class_project_dayinweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectintro',
            name='project_acquisition',
        ),
        migrations.RemoveField(
            model_name='projectintro',
            name='project_recommend',
        ),
        migrations.AddField(
            model_name='project',
            name='project_term_detail',
            field=models.CharField(default='-', max_length=100, verbose_name='프로젝트 상세 기간'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_time',
            field=models.CharField(max_length=100, verbose_name='프로젝트 시간'),
        ),
    ]
