# Generated by Django 2.2.6 on 2020-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20200413_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category/image/2020/04/16/Category_default.png', upload_to='category/image/%Y/%m/%d', verbose_name='대표 이미지'),
        ),
        migrations.AddField(
            model_name='category',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='소개'),
        ),
    ]
