# Generated by Django 2.2.6 on 2020-05-11 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20200416_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('correct_text', models.TextField(verbose_name='정답 시 멘트')),
                ('wrong_text', models.TextField(verbose_name='오답 시 멘트')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='프로젝트')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답')),
                ('correct', models.BooleanField(verbose_name='정답 여부')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Quiz', verbose_name='퀴즈')),
            ],
        ),
    ]
