# Generated by Django 2.2.6 on 2019-11-05 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
class Migration(migrations.Migration):
   dependencies = [
       migrations.swappable_dependency(settings.AUTH_USER_MODEL),
       ('payment', '0001_initial'),
   ]
   operations = [

   ]