# Generated by Django 2.2.6 on 2019-11-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191106_2349'),
        ('payment', '0002_auto_20191105_2045'),
    ]

    operations = [
    ]
