# Generated by Django 2.2.6 on 2019-11-12 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20191106_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='payment',
        ),
        migrations.AddField(
            model_name='apply',
            name='order_id',
            field=models.CharField(blank=True, max_length=13, verbose_name='주문 번호'),
        ),
        migrations.AddField(
            model_name='apply',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='가격'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='apply',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.Apply', verbose_name='신청'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='card', max_length=10, verbose_name='결제 수단'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='purchased_at',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='결제 승인 시각'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_id',
            field=models.CharField(default='fdsacdsa', max_length=200, verbose_name='영수증 ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='requested_at',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='결제 요청 시각'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=1525356, verbose_name='결제 상태'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='결제검증 여부'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='결제여부'),
        ),
    ]
