# Generated by Django 2.2.6 on 2019-11-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191112_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='order_id',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='주문 번호'),
        ),
    ]
