# Generated by Django 2.2.6 on 2019-11-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20191112_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to='payment.Apply', verbose_name='해당 신청'),
        ),
    ]
