# Generated by Django 2.2.6 on 2019-11-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20191112_0116'),
        ('payment', '0003_merge_20191108_0107'),
    ]

    operations = [
    ]
