# Generated by Django 2.2.6 on 2019-11-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_coupon_apply'),
        ('payment', '0005_merge_20191112_2019'),
    ]

    operations = [
    ]
