# Generated by Django 2.2.6 on 2019-11-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.CharField(default=1000, max_length=20, verbose_name='가격'),
            preserve_default=False,
        ),
    ]
