# Generated by Django 2.2.6 on 2019-11-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_price'),
        ('payment', '0006_merge_20191119_1553'),
    ]

    operations = [
    ]
