# Generated by Django 2.2.6 on 2019-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20191203_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='due',
            field=models.DateTimeField(verbose_name='마감기한'),
        ),
    ]
