# Generated by Django 2.2.6 on 2019-12-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_merge_20191129_1058'),
        ('payment', '0012_auto_20191203_1238'),
    ]

    operations = [
    ]
