# Generated by Django 2.2.6 on 2019-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20191203_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='취소여부'),
        ),
    ]
