# Generated by Django 2.2.6 on 2020-01-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_apply_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='수량'),
        ),
    ]
