# Generated by Django 2.2.6 on 2020-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20200117_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_price',
            field=models.PositiveIntegerField(default=999999999, verbose_name='최대 가격'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='최소 가격'),
        ),
    ]
