# Generated by Django 2.2.6 on 2020-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20200117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='identifier',
            field=models.CharField(blank=True, max_length=10, verbose_name='식별자'),
        ),
    ]
