# Generated by Django 2.2.6 on 2020-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20200317_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='영수증 링크'),
        ),
    ]
