# Generated by Django 2.2.6 on 2020-04-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_payment_receipt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='project',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
