# Generated by Django 2.2.6 on 2020-04-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20200414_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='paytoken',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='토스_페이토큰'),
        ),
    ]
