# Generated by Django 2.2.6 on 2019-10-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainBanners',
            new_name='MainBanner',
        ),
        migrations.RenameModel(
            old_name='SubBanners',
            new_name='SubBanner',
        ),
    ]
