# Generated by Django 2.2.6 on 2020-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsite', '0003_auto_20191023_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='이벤트명')),
                ('url_id', models.CharField(max_length=20, verbose_name='url 식별자')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
            },
        ),
    ]
