# Generated by Django 2.2.6 on 2020-04-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsite', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='subbanner',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
    ]
