# Generated by Django 2.2.6 on 2020-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsite', '0005_auto_20200413_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='태크'),
        ),
    ]
