# Generated by Django 2.2.6 on 2020-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsite', '0006_mainbanner_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='태그'),
        ),
    ]
