# Generated by Django 2.2.6 on 2019-10-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_hot'),
        ('accounts', '0002_auto_20191023_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='참여한 프로젝트'),
        ),
    ]
