# Generated by Django 2.2.6 on 2019-10-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_project_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', '여'), ('M', '남')], max_length=100, null=True, verbose_name='성별'),
        ),
    ]
