# Generated by Django 2.2.6 on 2019-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191023_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_1',
            field=models.BooleanField(default=True, verbose_name='이메일 수신 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_2',
            field=models.BooleanField(default=True, verbose_name='문자 수신 동의'),
        ),
    ]
