# Generated by Django 2.2.6 on 2019-11-15 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191106_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_number', models.IntegerField(blank=True, verbose_name='인증번호')),
                ('expired_time', models.DateTimeField(verbose_name='인증번호 만료시각')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
    ]
