# Generated by Django 2.2.6 on 2019-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_smsauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=12, verbose_name='이름'),
        ),
    ]
