# Generated by Django 2.2.6 on 2019-12-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191201_1118'),
        ('accounts', '0009_auto_20191203_0301'),
    ]

    operations = [
    ]
