# Generated by Django 2.2.6 on 2019-12-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191211_1755'),
        ('accounts', '0010_merge_20191203_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project_enrolled',
        ),
        migrations.AddField(
            model_name='user',
            name='project_enrolled',
            field=models.ManyToManyField(blank=True, related_name='project_enrolling', to='projects.Project', verbose_name='참여한 프로젝트'),
        ),
    ]
