# Generated by Django 2.2.6 on 2020-04-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191211_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project_enrolled',
        ),
    ]
