# Generated by Django 2.2.6 on 2020-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_project_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsauth',
            name='user',
        ),
        migrations.AddField(
            model_name='smsauth',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, verbose_name='휴대폰번호'),
        ),
    ]
